name: Backlog Labeller
description: Automatically manages the backlog label for issues
inputs:
  token:
    description: GitHub API token
    required: true
runs:
  using: docker
  image: docker://docker.io/nacx/backlog-labeller:56908b1f6217665c356cb00d2061d84b0b2d7ae4
  args:
    - '-token'
    - ${{ inputs.token }}
