name: 'Backlog Labeller'
description: 'Automatically manages the backlog label for issues'
inputs:
  token:  # id of input
    description: 'GitHub API token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '-token'
    - ${{ inputs.token }}
